CC = gcc
CFLAGS = -Wall -Wextra -pedantic -std=c99

TARGET = progetto11

all: $(TARGET)

$(TARGET): Progetto11_GrafoListeAdiacenza.c
	$(CC) $(CFLAGS) -o $(TARGET) Progetto11_GrafoListeAdiacenza.c

clean:
	rm -f $(TARGET)
