CREATE TABLE IF NOT EXISTS domande (
  id INT AUTO_INCREMENT PRIMARY KEY,
  id_utente INT NOT NULL,
  id_smalto VARCHAR(8) NOT NULL,
  domanda TEXT NOT NULL,
  data_domanda DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (id_utente) REFERENCES utenti(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS risposte (
  id INT AUTO_INCREMENT PRIMARY KEY,
  id_domanda INT NOT NULL,
  id_utente INT NOT NULL,
  risposta TEXT NOT NULL,
  utilita INT NOT NULL DEFAULT 0,
  data_risposta DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (id_domanda) REFERENCES domande(id),
  FOREIGN KEY (id_utente) REFERENCES utenti(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
