CREATE TABLE IF NOT EXISTS faq (
  id INT AUTO_INCREMENT PRIMARY KEY,
  domanda VARCHAR(255) NOT NULL,
  risposta TEXT NOT NULL,
  ordine INT NOT NULL DEFAULT 0,
  visibile BOOLEAN NOT NULL DEFAULT TRUE,
  data_creazione DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
