CREATE TABLE IF NOT EXISTS recensioni (
  id INT AUTO_INCREMENT PRIMARY KEY,
  id_utente INT NOT NULL,
  id_smalto VARCHAR(8) NOT NULL,
  titolo VARCHAR(80) NOT NULL,
  testo TEXT NOT NULL,
  voto TINYINT NOT NULL,
  utilita INT NOT NULL DEFAULT 0,
  data_pubblicazione DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  visibile BOOLEAN NOT NULL DEFAULT TRUE,
  FOREIGN KEY (id_utente) REFERENCES utenti(id),
  CHECK (voto BETWEEN 1 AND 5)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
