CREATE TABLE IF NOT EXISTS utenti (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nome VARCHAR(32) NOT NULL,
  cognome VARCHAR(32) NOT NULL,
  username VARCHAR(16) NOT NULL UNIQUE,
  email VARCHAR(64) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  tipo_utente ENUM('registrato','amministratore') NOT NULL DEFAULT 'registrato',
  crediti INT UNSIGNED NOT NULL DEFAULT 0,
  reputazione INT UNSIGNED NOT NULL DEFAULT 0,
  data_registrazione DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ban BOOLEAN NOT NULL DEFAULT FALSE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
